# Generated by Django 5.2 on 2025-04-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='icon',
            new_name='icon_url',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='icon',
            new_name='icon_url',
        ),
    ]
