# Generated by Django 5.2 on 2025-05-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_birthday_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorizationuserdata',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='registrationuserdata',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
