# Generated by Django 5.2 on 2025-05-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_authorizationuserdata_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pwd_hash',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pwd_salt',
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
