# Generated by Django 5.2 on 2025-05-21 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField()),
                ('street', models.CharField()),
                ('building_number', models.CharField()),
                ('appartment_number', models.IntegerField()),
                ('entrance_number', models.IntegerField()),
                ('intercom', models.CharField()),
                ('comment', models.CharField(default='', max_length=128)),
                ('is_default', models.BooleanField()),
                ('coordinates', models.CharField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
