# Generated by Django 5.2 on 2025-05-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_paymentmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='appartment_number',
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='apartment_number',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='entrance_number',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='intercom',
            field=models.CharField(default=''),
        ),
    ]
