# Generated by Django 5.2 on 2025-05-24 19:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_order_total_price_orderitem_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemingredient',
            name='state',
            field=models.CharField(choices=[('add', 'Add'), ('remove', 'Remove')], default='add', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_expected',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 24, 19, 19, 42, 218495, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.restaurant'),
        ),
    ]
