# Generated by Django 5.2 on 2025-05-25 08:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_orderitemingredient_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='short_description',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_expected',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='description',
            field=models.CharField(max_length=1024),
        ),
        migrations.CreateModel(
            name='FavouriteTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
