# Generated by Django 5.2 on 2025-05-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_pizza_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='apartment_number',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='entrance_number',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='intercom',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
