services:
    backend:
        ports:
            - ":3001"
        build: ./backend
        networks:
            - main_network
        env_file:
            - ./backend/.env
    frontend:
        ports:
            - ":3000"
        build: ./frontend
        networks:
            - main_network
        depends_on:
            - backend
    nginx:
        ports:
            - "80:80"
            - "443:443"
        build: ./nginx
        networks:
            - main_network
        depends_on:
            - backend
            - frontend
        environment:
            - SERVICE_FRONTEND_HOST=frontend
            - SERVICE_FRONTEND_PORT=3000
            - SERVICE_BACKEND_HOST=backend
            - SERVICE_BACKEND_PORT=3001
        volumes:
            - ./nginx/ssl-setup.conf:/etc/nginx/conf.d/ssl-setup.conf
            - ./nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template
            - ./nginx/images:/var/www/static/imgs/
            - /etc/certs:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
    certbot:
        env_file:
            - ./certbot/.env
        volumes:
            - /etc/certs:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        build: ./certbot
        profiles:
            - excluded
networks:
    main_network:
        name: main_network